 # For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: MaXiaoqing Blog
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/" # the subpath of the site
url: "https://jluqing.github.io" # the base hostname & protocol for the site
og_image: /assets/img/icons/wechat.png
google_analytics: "UA-121636368-3"


header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: 2579778804@qq.com
      link: mailto:yourmail@domain.com
    - name: WeChat
      value: ma199989
      link: "#"
  follow:
  
    - name: GitHub
      link: http://jluqing.github.io/YourGitHubUsername
    - name: Weibo
      link: http://weibo.com/u/YourWeiboUsername
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
